export enum AdminOpEnum {
  DEPARMENTS = 'Dept',
  APPLY_DISCOUNT = 'Apply Discount',
  EMPLZ = 'Daily Inv RPRT',
  SYSZ = 'Daily PMNT Type',
  WTDZ = 'Day Close',
  CHANGE_PRINTER = 'Change Printer',
  CLOSE_BROWSER = 'Close Browser',
  CANCEL_CHECK = 'Cancel Check',
  REMOVE_HOLD = 'Remove a hold',
  AUTH_PENDING = 'Pending Auth',
  BACK_USER = 'Back User',
  SET_USER = 'Set User',
  CLOSE_BATCH = 'Close Batch',
  CONFIG = 'Config',
  SYSTEM_VERSION = 'System Version',
  PREV_SCREEN = 'Prev Screen',
  CHARGE_ACCT_SETUP = 'Change Acct Setup',
  EMPLOYEE_SETUP = 'Employee Setup',
  CHANGE_PRICES = 'Change Prices',
  EBT_INQUIRY = 'EBT Inquiry'
}
